### ISSUE TITLE
I'm not able to run SoundDriftPlayer on my Windows 10 PC

### ISSUE THREAD

**Issue by iceberg53** [heymeowcat/SoundDriftPlayer#1]
When I run the SoundDrift-1.0.0.Setup file on my computer, I get an error as described below : 

<img width="418" alt="sound-drift_error" src="https://github.com/user-attachments/assets/619afecd-010b-46a4-b59b-d6a5d2cff6ce">

It appears to be related to an instruction for setting the icon but this is what I've been able to spot so far. 

And thanks for your time.

**Comment by heymeowcat** [comment]
This issue has been resolved in version 1.0.1. Please download the new release from the  [Releases page!](https://github.com/heymeowcat/SoundDriftPlayer/releases/tag/v1.0.1)

**Comment by iceberg53** [comment]
It runs fine now. Thanks
